### ISSUE TITLE
Free Signs

### ISSUE THREAD

**Issue by BobbyTowers** [PocketMine-PHP7/EssentialsPE-PHP7#1]
Can you add back the use of free signs?

**Comment by flaxues** [comment]
They stil work you neem to gave yourself permissions 

essentials.sign.use.free

**Comment by BobbyTowers** [comment]
I gave my self the right permissions but it still don't work.

**Comment by flaxues** [comment]
What does it say nothing or ...

**Comment by BobbyTowers** [comment]
It tells me that signs are banned on this server when I try and use one. I have op so it should work with out permissions.

**Comment by flaxues** [comment]
You mean all the signs are banned?

**Comment by BobbyTowers** [comment]
![screenshot_2016-02-12-13-01-52](https://cloud.githubusercontent.com/assets/12857229/13015799/12347610-d189-11e5-9c1b-838aa0ff94a3.png)

Looks like it.

**Comment by flaxues** [comment]
Could you post you're plugins?

**Comment by BobbyTowers** [comment]
I removed all the plugins and just left Essentials and it still does the same thing.

![screenshot_2016-02-12-13-13-58](https://cloud.githubusercontent.com/assets/12857229/13016068/98f07284-d18a-11e5-85f7-c4026dae73fb.png)

**Comment by flaxues** [comment]
It works on my server...

**Comment by flaxues** [comment]
Could you put you're debug-level to 3 in you're pocketmine.yml and restart the server and try to use the sign again and post the error or messages that are sayed by the console?

**Comment by flaxues** [comment]
Wait are you in gamemode 1? If so change to survival

**Comment by BobbyTowers** [comment]
I'm in survival.

[13:48:19] system> [TC] Server will restart in 60 mins.
[13:48:29] debug> [EssentialsPE] Creating player session file...
[13:48:29] debug> [EssentialsPE] Creating virtual session...
[13:48:29] debug> [EssentialsPE] Setting up new values...
[13:48:29] debug> [EssentialsPE] Setting up final values...
[13:48:29] system> BobbyTowers[/73.49.36.198:62311] logged in with entity id 1 at (world, 1, 6, 1)
[13:48:30] debug> [PurePerms] Registering player BobbyTowers...
[13:48:30] system> BobbyTowers joined the game.
[13:48:48] debug> Running EssentialsPE's AFKSetterTask
[13:49:18] debug> Running EssentialsPE's AFKSetterTask
[13:49:19] system> [TC] Server will restart in 59 mins.

**Comment by flaxues** [comment]
So between 13:48:19 until 13:49:19 you used the sign?

**Comment by BobbyTowers** [comment]
Yes

**Comment by flaxues** [comment]
https://transfer.sh/EVwTi/essentialspe-v1.1.3.phar

Could you use this phar? And try it again?

**Comment by BobbyTowers** [comment]
That did it and Thank You!

**Comment by flaxues** [comment]
Ummm i wouldn't use it. I just changed the permissions to everyone the problem is on you're side you didn't configured permissions right...

**Comment by flaxues** [comment]
Use this one:

https://github.com/PocketMine-PHP7/EssentialsPE-PHP7/blob/master/EssentialsPE.phar?raw=true

And configure you're permissions correctly
